version: '1.0'
name: pipeline-20231101
displayName: pipeline-20231101
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-12f6f333
    displayName: master
    strategy: naturally
    trigger: auto
    executor:
      - '674074365'
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
      - step: ut@nodejs
        name: unit_test_nodejs
        displayName: Nodejs 单元测试
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 在这里输入测试命令'
          - npm install && npm run test
        report:
          path: mochawesome-report
          file: mochawesome.json
          index: mochawesome.html
        checkpoints: []
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
