version: '1.0'
name: pipeline-20231101
displayName: pipeline-20231101
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-12f6f333
    displayName: master
    strategy: naturally
    trigger: auto
    executor:
      - '674074365'
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: aliyun
          hostID:
            - bb964ef3-3ef5-4847-af27-ba54e5d31072
        script:
          - '# 请在此输入您想执行的脚本'
          - echo 'Hello Gitee!'
        notify: []
        strategy:
          retry: '0'
