version: '1.0'
name: pipeline-20231101
displayName: pipeline-20231101
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-12f6f333
    displayName: master
    strategy: naturally
    trigger: auto
    executor:
      - '674074365'
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
      - step: ut@nodejs
        name: unit_test_nodejs
        displayName: Nodejs 单元测试
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 在这里输入测试命令'
          - npm install && npm run test
        report:
          path: mochawesome-report
          file: mochawesome.json
          index: mochawesome.html
        checkpoints: []
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: aliyun
          hostID:
            - bb964ef3-3ef5-4847-af27-ba54e5d31072
        deployArtifact:
          - source: artifact
            name: output
            target: ~/gitee_go/deploy
            artifactRepository: default
            artifactName: output
            artifactVersion: latest
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - '# mkdir -p /home/admin/app'
          - '# tar zxvf ~/gitee_go/deploy/output.tar.gz -C /home/admin/app'
          - '# sh /home/admin/app/deploy.sh restart'
          - '# 如果你是php之类的无需制品包的制品方式，可以使用 git clone 或者 git pull 将源代码更新到服务器，再执行其他命令'
          - '# git clone ***@***.git'
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: aliyun
          hostID:
            - bb964ef3-3ef5-4847-af27-ba54e5d31072
        script:
          - '# 请在此输入您想执行的脚本'
          - echo 'Hello Gitee!'
        notify: []
        strategy:
          retry: '0'
